openapi: "3.0.2"
info:
  title: Common API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths: { }
components:
  schemas:
    BaseResourceResponse:
      type: object
      required:
        - externalId
        - createdAt
        - updatedAt
      properties:
        externalId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        createdAt:
          type: string
          format: date-time
          example: '2023-01-02T12:00:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-01-02T12:00:00Z'
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
            example: "Something went wrong"
