openapi: "3.0.2"
info:
  title: Common API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths: { }
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
            example: "Something went wrong"
