//package com.ebsolutions.applications.whoami.user;
//
//import org.mapstruct.Mapper;
//import org.mapstruct.Mapping;
//import org.mapstruct.factory.Mappers;
//
//@Mapper(componentModel = "spring")
//public interface AppUserMapper {
//
//  AppUserMapper INSTANCE = Mappers.getMapper(AppUserMapper.class);
//
//  // Map DTO -> Entity
//  @Mapping(target = "id", ignore = true)          // ID is generated by DB
//  @Mapping(target = "createdAt", expression = "java(java.time.LocalDateTime.now())")
//  AppUser toEntity(AppUserSto sto);
//
//  // Map Entity -> STO
//  AppUser toSto(AppUser entity);
//}
