application:
  persistence:
    database: auth
    port: 5432
    schema: auth

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  health:
    enabled: true
  info:
    env:
      enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://${application.persistence.hostname}:${application.persistence.port}/${application.persistence.database}?currentSchema=${application.persistence.schema}
    username: ${application.persistence.username}
    password: ${application.persistence.password}
  main:
    banner-mode: off
  mvc:
    # Required for Spring MVC to throw NoHandlerFoundException for unmapped endpoints
    # This is caught in the GlobalExceptionHandler as a 404 error
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # Required for Spring MVC to throw NoHandlerFoundException for unmapped endpoints
      # This is caught in the GlobalExceptionHandler as a 404 error
      add-mappings: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
