application:
  persistence:
    hostname: localhost
    password: CHANGE_ME
    username: auth_app_user

logging:
  level:
    root: OFF # Shows logs from application
    # root: INFO # Shows logs from application
    org:
      springframework: OFF # Disable all Spring Framework logs
      # springframework: INFO # Disable all Spring Framework logs