application:
  persistence:
    hostname: localhost
    password: CHANGE_ME
    username: auth_app_user

logging:
  level:
    root: INFO
  org:
    springframework: INFO

spring:
  main:
    banner-mode: on