<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ebsolutions.applications.whoami</groupId>
        <artifactId>who-am-i-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>who-am-i-service</artifactId>
    <name>Who Am I Service</name>
    <packaging>jar</packaging>

    <properties>
        <start-class>com.ebsolutions.applications.whoami.Application</start-class>

        <argLine></argLine>

        <!-- Sonar Configurations -->
        <sonar.coverage.jacoco.xmlReportPaths>
            target/site/jacoco/jacoco.xml
        </sonar.coverage.jacoco.xmlReportPaths>
        <sonar.coverage.exclusions>
            **/Application.java,
            **/config/*,
            **/model/*,
            **/*Generator.java
        </sonar.coverage.exclusions>

        <!-- Versions: Dependencies: Service -->
        <jackson-databind-nullable.version>0.2.10</jackson-databind-nullable.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <springdoc-openapi-starter-webmvc-ui.version>2.8.16</springdoc-openapi-starter-webmvc-ui.version>

        <!-- Versions: Dependencies: Testing -->
        <cucumber-bom.version>7.31.0</cucumber-bom.version>
        <junit-bom.version>6.0.1</junit-bom.version>
        <!-- This must match what is in Spring Parent -->
        <mockito.version>5.17.0</mockito.version>

    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Dependency Management: BOMs : Start -->

            <!-- Used for Cucumber BDD testing libs-->
            <!-- Version: Explicit -->
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-bom</artifactId>
                <version>${cucumber-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Used for JUnit and Mockito testing libs-->
            <!-- Version: Explicit -->
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Dependency Management: BOMs : End -->

            <!-- Dependency Management: Individual : Start -->

            <!-- MapStruct annotation processor for compile time annotations -->
            <!-- Version: Explicit -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <!-- Dependency Management: Individual : End -->

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Dependencies: Compile : Start -->

        <!-- Used for Swagger and serialization of Local Date -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <!-- Used for mapping between OpenAPI DTO and database entity -->
        <!-- Version: Explicit -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>

        <!-- Used for the validation annotations -->
        <!-- Version: Explicit -->
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>${jackson-databind-nullable.version}</version>
        </dependency>

        <!-- Used for Swagger UI and Open API annotations -->
        <!-- Version: Explicit -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc-openapi-starter-webmvc-ui.version}</version>
        </dependency>

        <!-- Exposes the actuator API health/info/etc. -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Used for database framework -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
        </dependency>

        <!-- Used for authentication -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <!-- Used for validation annotations in Controller, etc. -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- Contains Spring Boot Starter and Tomcat web server -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- Dependencies: Compile : End -->

        <!-- Dependencies: Runtime : Start -->

        <!-- Required for driver class: org.postgresql.Driver -->
        <!-- Version: Installed on runtime machine -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Dependencies: Runtime : End -->

        <!-- Dependencies: Test : Start -->

        <!-- Testing linkage between Cucumber and Java -->
        <!-- Version: Dependency Management - Cucumber BOM -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Testing linkage between Cucumber and JUnit -->
        <!-- Version: Dependency Management - Cucumber BOM -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Testing linkage between Cucumber and Spring context -->
        <!-- Version: Dependency Management - Cucumber BOM -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Needed for running tests in Junit -->
        <!-- Version: Dependency Management - Junit BOM -->
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Explicitly add Mockito core (no inline agent needed) -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Testing framework for starting Spring context and MockMVC -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <!-- Exclude mockito-inline to avoid self-attaching agent warning -->
                <exclusion>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-inline</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Used for Docker container during Acceptance tests -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Used for Docker container during Acceptance tests -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Used for Docker container during Acceptance tests -->
        <!-- Version: Spring Parent -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Dependencies: Test : End -->

    </dependencies>

    <build>
        <plugins>
            <!-- Maintains strict Code Styles -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>

            <!-- Used to compile the sources of your project -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>

                        <!-- Lombok must be prior to MapStruct -->
                        <!-- Used for POJO annotations within project -->
                        <!-- Version: Spring Parent -->
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>

                        <!-- MapStruct must be after Lombok -->
                        <!-- MapStruct annotation processor for compile time annotations -->
                        <!-- Version: Dependency Management -->
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                        </path>

                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <!-- Gives the actuator/info API build information -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <!-- Generates Java classes from OpenAPI contracts -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>${common-dto-id.executions}</id>
                    </execution>
                    <execution>
                        <id>${actuator-dto-id.executions}</id>
                    </execution>
                    <execution>
                        <id>${app-user-dto-id.executions}</id>
                    </execution>
                </executions>
            </plugin>

            <!-- Used to run agent that collects code coverage -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>jacoco-initialize</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <propertyName>argLine</propertyName>
                            <includes>
                                <include>com.ebsolutions.applications.whoami.*</include>
                            </includes>
                            <excludes>
                                <exclude>com.ebsolutions.applications.whoami.*</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Used for running class specific unit tests -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!--                    <skipTests>true</skipTests>-->
                    <argLine>${argLine}</argLine>
                    <testFailureIgnore>false</testFailureIgnore>
                    <includes>
                        <include>**/UnitTestRunner.*</include>
                    </includes>
                    <systemPropertyVariables>
                        <!-- This triggers the correct application-unit.yaml -->
                        <spring.profiles.active>unit</spring.profiles.active>
                    </systemPropertyVariables>
                </configuration>
            </plugin>

            <!-- Used for running the integration and acceptance tests -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <id>integration-tests</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <skipTests>true</skipTests>
                            <argLine>${argLine}</argLine>
                            <testFailureIgnore>false</testFailureIgnore>
                            <systemPropertyVariables>
                                <!-- This triggers the correct application-integration.yaml -->
                                <spring.profiles.active>integration</spring.profiles.active>
                            </systemPropertyVariables>
                            <includes>
                                <include>**/IntegrationTestRunner.*</include>
                            </includes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>acceptance-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <skipTests>true</skipTests>
                            <argLine>${argLine}</argLine>
                            <testFailureIgnore>false</testFailureIgnore>
                            <systemPropertyVariables>
                                <!-- This triggers the correct application-acceptance.yaml -->
                                <spring.profiles.active>acceptance</spring.profiles.active>
                            </systemPropertyVariables>
                            <includes>
                                <include>**/AcceptanceTestRunner.*</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Used to integrate SonarQube analysis into the Maven build -->
            <!-- Version: Parent POM - Plugin Management -->
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
            </plugin>

        </plugins>
    </build>

</project>