openapi: "3.1.0"
info:
  title: User API
  version: "1.0"
servers:
  - url: http://localhost:8080
components:
  schemas:
    AppUserResponse:
      allOf:
        - $ref: '../common.yaml#/components/schemas/BaseResourceResponse'
      type: object
      description: App user returned to clients
      required:
        - emailAddress
        - firstName
        - lastName
      properties:
        emailAddress:
          type: string
          format: email
          example: "johnny.appleseed@gmail.com"
        firstName:
          type: string
          example: "Johnny"
        lastName:
          type: string
          example: "Appleseed"
