openapi: "3.1.0"
info:
  title: App User Create STO
  version: "1.0"
servers:
  - url: http://localhost:8080
components:
  schemas:
    AppUserCreateRequest:
      type: object
      description: Payload for creating an app user
      properties:
        emailAddress:
          type: string
          format: email
          example: "johnny.appleseed@gmail.com"
        firstName:
          type: string
          example: Johnny
        lastName:
          type: string
          example: Appleseed
      required:
        - emailAddress
        - firstName
        - lastName
