openapi: "3.1.0"
info:
  title: User API
  version: "1.0"
servers:
  - url: http://localhost:8080
components:
  schemas:
    AppUserResponse:
      type: object
      description: App user returned to clients
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - userId
        - email
        - firstName
        - lastName
        - createdAt
        - updatedAt
